version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: monomart
      POSTGRES_USER: monomart
      POSTGRES_PASSWORD: monomart
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/monomart
      SPRING_DATASOURCE_USERNAME: monomart
      SPRING_DATASOURCE_PASSWORD: monomart
      MONOMART_JWT_SECRET: change-me-please-very-strong-secret
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:


