spring:
  application:
    name: ${APP_NAME:monomart-test}
  datasource:
    url: ${TEST_DB_URL:jdbc:h2:mem:testdb}
    username: ${TEST_DB_USERNAME:sa}
    password: ${TEST_DB_PASSWORD:}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        jdbc.lob.non_contextual_creation: true
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:true}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:false}

server:
  port: ${SERVER_PORT:0}

security:
  jwt:
    issuer: ${JWT_ISSUER:MonoMart-Test}
    access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION:5}
    refresh-token-expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION:1}
    secret: ${JWT_SECRET:test-secret-32-bytes-minimum-for-testing!}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    com.monomart: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.test: ${LOG_LEVEL_TEST:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics}

springdoc:
  api-docs:
    path: ${API_DOCS_PATH:/api-docs}
    enabled: ${API_DOCS_ENABLED:true}
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
    enabled: ${SWAGGER_UI_ENABLED:true}
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  info:
    title: ${API_TITLE:MonoMart Test API}
    description: ${API_DESCRIPTION:Single-vendor e-commerce backend API - Test Environment}
    version: ${API_VERSION:1.0.0-test}
    contact:
      name: ${API_CONTACT_NAME:MonoMart Test Support}
      email: ${API_CONTACT_EMAIL:test@monomart.local}
